//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetRocks.Web.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetRocks.Web.Resources.Texts.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尊敬的用户，&lt;br /&gt; 您好， 这封信是由 .Net Rocks 自动发送。 &lt;br /&gt;您收到这封邮件，是由于在 .Net Rocks 进行了新用户注册，或用户修改 有效电子邮箱 使用 了这个邮箱地址。如果您并没有访问过 .Net Rocks，或没有进行上述操作，请忽略这封邮件。您不需要退订或进行其他进一步的操作。&lt;br /&gt;----------------------------------------------------------------------&lt;br /&gt;&lt;strong&gt;帐号激活说明&lt;/strong&gt;&lt;br /&gt;----------------------------------------------------------------------&lt;br /&gt;如果您是 .Net Rocks 的新用户，或在修改您的 有效电子邮箱地址 时使用了本地址，我们需 要对您的邮箱地址进行有效验证以避免垃圾邮件或地址被滥用。&lt;br /&gt;您只需点击下面的链接即可激活您的帐号：&lt;br /&gt;{0}&lt;br /&gt;(如果上面不是链接形式，请将该地址手工粘贴到浏览器地址栏再访问)&lt;br /&gt;&lt;br /&gt;感谢您的 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ValidEmail_Body {
            get {
                return ResourceManager.GetString("ValidEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Rocks - 邮箱地址验证。.
        /// </summary>
        public static string ValidEmail_Subject {
            get {
                return ResourceManager.GetString("ValidEmail_Subject", resourceCulture);
            }
        }
    }
}
